version: '3.9'
services:
  db:
    restart: always
    image: postgres:16.10-alpine
    container_name: my_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mydb
volumes:
  postgres-data:
